### ISSUE TITLE
使用deepctr 包 DCN 训练模型没有报错，但是 model = tf.keras.models.load_model('model_657.h5') 会报错， ValueError: Unknown layer: DNN

### ISSUE THREAD

**Issue by huminwudi** [shenweichen/DeepCTR#107]
**Describe the question(问题描述)**
A clear and concise description of what the question is.

**Additional context**

**Operating environment(运行环境):**
 - python version [e.g. 3.6]
 - tensorflow version [e.g. 1.4.0,]
 - deepctr version [e.g. 0.3.2,]

**Comment by shenweichen** [comment]
please use the following codes to load the model
```python
from tensorflow.python.keras.models import  save_model,load_model
model = DeepFM()
save_model(model, 'DeepFM.h5')# save_model, same as before

from deepctr.layers import custom_objects
model = load_model('DeepFM.h5',custom_objects)# load_model,just add a parameter
```

**Comment by SongRb** [comment]
When using `custom_object` like this:
```
model = keras.models.load_model(model_path, custom_objects=custom_objects)
```
The `model` is expected to be a `FiBiNet` instance and I got the following error:
```
Traceback (most recent call last):
  File "/home/tang/Code/kinrong/aScoreModel101/deep_cross.py", line 203, in <module>
    main('FiBiNET')
  File "/home/tang/Code/kinrong/aScoreModel101/deep_cross.py", line 123, in main
    model = load_keras_model('models/20190808-0802-fibinet/15.hd5')
  File "/home/tang/Code/kinrong/aScoreModel101/deep_cross.py", line 198, in load_keras_model
    model = keras.models.load_model(model_path, custom_objects=custom_objects)
  File "/home/tang/anaconda3/envs/fraudect/lib/python3.6/site-packages/keras/engine/saving.py", line 419, in load_model
    model = _deserialize_model(f, custom_objects, compile)
  File "/home/tang/anaconda3/envs/fraudect/lib/python3.6/site-packages/keras/engine/saving.py", line 225, in _deserialize_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/home/tang/anaconda3/envs/fraudect/lib/python3.6/site-packages/keras/engine/saving.py", line 458, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/home/tang/anaconda3/envs/fraudect/lib/python3.6/site-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/home/tang/anaconda3/envs/fraudect/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 145, in deserialize_keras_object
    list(custom_objects.items())))
  File "/home/tang/anaconda3/envs/fraudect/lib/python3.6/site-packages/keras/engine/network.py", line 1022, in from_config
    process_layer(layer_data)
  File "/home/tang/anaconda3/envs/fraudect/lib/python3.6/site-packages/keras/engine/network.py", line 1008, in process_layer
    custom_objects=custom_objects)
  File "/home/tang/anaconda3/envs/fraudect/lib/python3.6/site-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/home/tang/anaconda3/envs/fraudect/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 147, in deserialize_keras_object
    return cls.from_config(config['config'])
  File "/home/tang/anaconda3/envs/fraudect/lib/python3.6/site-packages/keras/engine/base_layer.py", line 1109, in from_config
    return cls(**config)
  File "/home/tang/anaconda3/envs/fraudect/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/tang/anaconda3/envs/fraudect/lib/python3.6/site-packages/keras/layers/core.py", line 848, in __init__
    self.kernel_initializer = initializers.get(kernel_initializer)
  File "/home/tang/anaconda3/envs/fraudect/lib/python3.6/site-packages/keras/initializers.py", line 508, in get
    return deserialize(identifier)
  File "/home/tang/anaconda3/envs/fraudect/lib/python3.6/site-packages/keras/initializers.py", line 503, in deserialize
    printable_module_name='initializer')
  File "/home/tang/anaconda3/envs/fraudect/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 138, in deserialize_keras_object
    ': ' + class_name)
ValueError: Unknown initializer: GlorotUniform
```

Env info:
`tensorflow-gpu=1.14.0`
`python=3.6`
`deepctr[gpu]=0.6.0`

**Comment by ueqt** [comment]
@SongRb 
It worked with tensorflow keras 
```
model = tensorflow.keras.models.load_model(model_path, custom_objects=custom_objects)
```
