### ISSUE TITLE
Din模型调用报错

### ISSUE THREAD

**Issue by waterbeach** [shenweichen/DeepCTR#117]
报的错误如下：
Traceback (most recent call last):
  File "ctr_din.py", line 243, in <module>
    model = DIN(linear_feature_columns, behavior_feature_list, hist_len_max=200)
  File "/home/dm/software/anaconda2/lib/python3.6/site-packages/deepctr/models/din.py", line 82, in DIN
    keys_emb = concat_fun(keys_emb_list)
  File "/home/dm/software/anaconda2/lib/python3.6/site-packages/deepctr/layers/utils.py", line 67, in concat_fun
    return tf.keras.layers.Concatenate(axis=axis)(inputs)
  File "/home/dm/software/anaconda2/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 694, in __call__
    in_deferred_mode = isinstance(input_list[0], DeferredTensor)
IndexError: list index out of range

请问这是什么原因报错呢？

**Comment by shenweichen** [comment]
建议先看下examples文件夹里的run_din.py文件，再在自己的数据上运行该模型
