### ISSUE TITLE
How can I use MLR model?

### ISSUE THREAD

**Issue by CalvinNeo** [shenweichen/DeepCTR#174]
Please refer to the [FAQ](https://deepctr-doc.readthedocs.io/en/latest/FAQ.html) in doc and search for the [related issues](https://github.com/shenweichen/DeepCTR/issues) before you ask the question.

**Describe the question(问题描述)**
I want to use the Piece-wise Linear Model to train a dataset organized by time. I want the dataset to be divided by the `"matchclock"` column, so I wrote the following codes
```
base_columns = list(set(x_train.columns) - set(['matchclock']))
model = MLR(x_train[['matchclock']], base_feature_columns=x_train[base_columns], region_num=4, l2_reg_linear=1e-5,init_std=0.0001, seed=1024, task='binary')
model.compile("adam", "binary_crossentropy",
          metrics=['binary_crossentropy'], )
history = model.fit(x_train, y_train.values,
                    batch_size=256, epochs=10, verbose=2, validation_split=0.2, )
```
However it prints out some errors
```
Traceback (most recent call last):
  File ".\smooth_on_deepctr.py", line 202, in <module>
    model = get_compiled_model_mlr("")
  File ".\smooth_on_deepctr.py", line 147, in get_compiled_model_mlr
    model = MLR(x_train[['matchclock']], base_feature_columns=x_train[base_columns], region_num=4,l2_reg_linear=1e-5,init_std=0.0001, seed=1024, task='binary')
  File "E:\Programs\Anaconda2\envs\py3\lib\site-packages\deepctr\models\mlr.py", line 43, in MLR
    features = build_input_features(region_feature_columns + base_feature_columns + bias_feature_columns)
  File "E:\Programs\Anaconda2\envs\py3\lib\site-packages\pandas\core\ops\__init__.py", line 1488, in f
    other = _align_method_FRAME(self, other, axis)
  File "E:\Programs\Anaconda2\envs\py3\lib\site-packages\pandas\core\ops\__init__.py", line 1458, in _align_method_FRAME
    right = to_series(right)
  File "E:\Programs\Anaconda2\envs\py3\lib\site-packages\pandas\core\ops\__init__.py", line 1419, in to_series
    msg.format(req_len=len(left.columns), given_len=len(right))
ValueError: Unable to coerce to Series, length must be 217: given 0
```

**Additional context**

**Operating environment(运行环境):**
 - python version 3.6.9
 - tensorflow version 1.15.0
 - deepctr version  0.7.0

**Comment by CalvinNeo** [comment]
Is this problem related to how to generate `x`? My `x` is a 2d pandas matrix with columns representing features and rows representing records

**Comment by CalvinNeo** [comment]
It compiles when I change `x`'s format
