### ISSUE TITLE
DIN run_din.py执行失败

### ISSUE THREAD

**Issue by jingbao12** [shenweichen/DeepCTR#189]
Please refer to the [FAQ](https://deepctr-doc.readthedocs.io/en/latest/FAQ.html) in doc and search for the [related issues](https://github.com/shenweichen/DeepCTR/issues) before you ask the question.

**Describe the question(问题描述)**
run DeepCTR-0.7.2/examples/run_din.py failed

**Additional context**
Traceback (most recent call last):
  File "run_din.py", line 39, in <module>
    history = model.fit(x, y, verbose=1, epochs=10, validation_split=0.5)
  File "/home/s/apps/CloudSearch/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 819, in fit
    use_multiprocessing=use_multiprocessing)
  File "/home/s/apps/CloudSearch/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 235, in fit
    use_multiprocessing=use_multiprocessing)
  File "/home/s/apps/CloudSearch/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 533, in _process_training_inputs
    adapter_cls = data_adapter.select_data_adapter(x, y)
  File "/home/s/apps/CloudSearch/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/data_adapter.py", line 998, in select_data_adapter
    _type_name(x), _type_name(y)))
ValueError: Failed to find data adapter that can handle input: (<class 'dict'> containing {"<class 'str'>"} keys and {"<class 'numpy.ndarray'>"} values), (<class 'list'> containing values of types {"<class 'int'>"})

**Operating environment(运行环境):**
 - python version 3.7.4
 - tensorflow version 2.1.0
 - deepctr version 0.7.2

**Comment by shenweichen** [comment]
先用1.x版本试下，2.0可能有一些兼容性的问题

**Comment by jhhugo** [comment]
报错写得很清楚了，都要numpy.array格式，run_din.py里面，y = [1, 0, 1]改成y = np.array([1, 0, 1])
