### ISSUE TITLE
feature_column import error problem

### ISSUE THREAD

**Issue by kang1916** [shenweichen/DeepCTR#245]
**Describe the question**
feature_column import error when run "python run_classification_criteo.py" after updating to deepctr version 0.8.0

**Additional context**
It's ok to run all scripts before updating to this new version. And it's also ok to run estimator demos. 
Full context is like this:
Traceback (most recent call last):
  File "run_classification_criteo.py", line 6, in <module>
    from deepctr.models import DeepFM
  File "build/bdist.linux-x86_64/egg/deepctr/models/__init__.py", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/deepctr/models/afm.py", line 14, in <module>
  File "build/bdist.linux-x86_64/egg/deepctr/feature_column.py", line 8, in <module>
  File "build/bdist.linux-x86_64/egg/deepctr/inputs.py", line 15, in <module>
ImportError: cannot import name feature_column

**Operating environment:**
 - python version [2.7]
 - tensorflow version [1.14.0]
 - deepctr version [e.g. 0.8.0]

Thanks for your time! : )

**Comment by shenweichen** [comment]
This may be caused by the import mechanism of python2, please try python3 first.

**Comment by kang1916** [comment]
> This may be caused by the import mechanism of python2, please try python3 .

Thanks, it helps!
