### ISSUE TITLE
feature_column和inputs有循环依赖

### ISSUE THREAD

**Issue by zscwind** [shenweichen/DeepCTR#252]
from deepctr.inputs import create_embedding_matrix
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/deepctr/inputs.py", line 15, in <module>
    from . import feature_column as fc_lib
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/deepctr/feature_column.py", line 8, in <module>
    from .inputs import create_embedding_matrix, embedding_lookup, get_dense_input, varlen_embedding_lookup, \
ImportError: cannot import name 'create_embedding_matrix'

**Comment by zscwind** [comment]
inputs.py中import feature_column.py；feature_column.py中import inputs.py，导致有循环依赖

**Comment by cyj1209** [comment]
I have the same problem 
ImportError cannot import name 'create_embedding_matrix' from 'deepctr.inputs'

**Comment by liuruihuang** [comment]
> inputs.py中import feature_column.py；feature_column.py中import inputs.py，导致有循环依赖

可以解决吗，我的是这样
>>> from deepctr.feature_column import SparseFeat
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/liuruihuang/.local/lib/python2.7/site-packages/deepctr/feature_column.py", line 8, in <module>
    from .inputs import create_embedding_matrix, embedding_lookup, get_dense_input, varlen_embedding_lookup, \
  File "/home/liuruihuang/.local/lib/python2.7/site-packages/deepctr/inputs.py", line 15, in <module>
    from . import feature_column as fc_lib
ImportError: cannot import name feature_column

**Comment by liuruihuang** [comment]
python2.7
把input.py里面的
from . import feature_column as fc_lib
改成
import feature_column as fc.lib
可以正常运行

**Comment by shenweichen** [comment]
hi ,we have solved this problem in deepctr v0.8.1,please use `pip install -U deepctr` to upgrade.
