### ISSUE TITLE
Error, just run "run_classification_criteo.py" in examples, tf version == 2.3.0

### ISSUE THREAD

**Issue by xinyu009** [shenweichen/DeepCTR#259]
Traceback (most recent call last):
  File "run_classification_criteo.py", line 45, in <module>
    model = DeepFM(linear_feature_columns, dnn_feature_columns, task='binary')
  File "/home/xinyu/anaconda3/lib/python3.7/site-packages/deepctr/models/deepfm.py", line 47, in DeepFM
    l2_reg=l2_reg_linear)
  File "/home/xinyu/anaconda3/lib/python3.7/site-packages/deepctr/feature_column.py", line 148, in get_linear_logit
    prefix=prefix + str(i))[0] for i in range(units)]
  File "/home/xinyu/anaconda3/lib/python3.7/site-packages/deepctr/feature_column.py", line 148, in <listcomp>
    prefix=prefix + str(i))[0] for i in range(units)]
  File "/home/xinyu/anaconda3/lib/python3.7/site-packages/deepctr/feature_column.py", line 184, in input_from_feature_columns
    group_sparse_embedding_dict = embedding_lookup(embedding_matrix_dict, features, sparse_feature_columns)
  File "/home/xinyu/anaconda3/lib/python3.7/site-packages/deepctr/inputs.py", line 87, in embedding_lookup
    group_embedding_dict[fc.group_name].append(sparse_embedding_dict[embedding_name](lookup_idx))
  File "/home/xinyu/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 926, in __call__
    input_list)
  File "/home/xinyu/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1098, in _functional_construction_call
    self._maybe_build(inputs)
  File "/home/xinyu/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 2643, in _maybe_build
    self.build(input_shapes)  # pylint:disable=not-callable
  File "/home/xinyu/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/utils/tf_utils.py", line 323, in wrapper
    output_shape = fn(instance, input_shape)
  File "/home/xinyu/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/layers/embeddings.py", line 142, in build
    constraint=self.embeddings_constraint)
  File "/home/xinyu/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 614, in add_weight
    caching_device=caching_device)
  File "/home/xinyu/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/tracking/base.py", line 750, in _add_variable_with_custom_getter
    **kwargs_for_getter)
  File "/home/xinyu/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer_utils.py", line 145, in make_variable
    shape=variable_shape if variable_shape else None)
  File "/home/xinyu/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/variables.py", line 260, in __call__
    return cls._variable_v1_call(*args, **kwargs)
  File "/home/xinyu/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/variables.py", line 221, in _variable_v1_call
    shape=shape)
  File "/home/xinyu/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/variables.py", line 199, in <lambda>
    previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)
  File "/home/xinyu/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/variable_scope.py", line 2597, in default_variable_creator
    shape=shape)
  File "/home/xinyu/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/variables.py", line 264, in __call__
    return super(VariableMetaclass, cls).__call__(*args, **kwargs)
  File "/home/xinyu/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 1518, in __init__
    distribute_strategy=distribute_strategy)
  File "/home/xinyu/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 1658, in _init_from_args
    (initial_value.shape, shape))
ValueError: The initial value's shape ((27, 4)) is not compatible with the explicitly supplied `shape` argument ((27, 1)).

**Comment by michael0905** [comment]
same issue
#262

**Comment by Magiclemond** [comment]
revise this command and try again:`fixlen_feature_columns = [SparseFeat(feat, vocabulary_size=data[feat].nunique(),embedding_dim=1,embeddings_initializer=tf.initializers.identity(np.zeros([data[feat].nunique(),1]))) for i,feat in enumerate(sparse_features)] + [DenseFeat(feat, 1,) for feat in dense_features]`

**Comment by shenweichen** [comment]
hi ,we have solved this problem in deepctr v0.8.1,please use `pip install -U deepctr` to upgrade.
