### ISSUE TITLE
call() missing 'state' argument when saving DIEN model

### ISSUE THREAD

**Issue by Litchilitchy** [shenweichen/DeepCTR#310]
I am running the example of DIEN
```
if __name__ == "__main__":
    if tf.__version__ >= '2.0.0':
        tf.compat.v1.disable_eager_execution()

    USE_NEG = True
    x, y, feature_columns, behavior_feature_list = get_xy_fd(use_neg=USE_NEG)

    model = DIEN(feature_columns, behavior_feature_list,
                 dnn_hidden_units=[4, 4, 4], dnn_dropout=0.6, gru_type="AUGRU", use_negsampling=USE_NEG)

    model.compile('adam', 'binary_crossentropy',
                  metrics=['binary_crossentropy'])
    history = model.fit(x, y, verbose=1, epochs=10, validation_split=0.5)
```

After training, I want to export savedModel using '
```
tf.saved_model.save(model, 'tf_dien')
```

but error is raised:
```
Train on 1 samples, validate on 2 samples
2020-12-23 14:19:42.393857: W tensorflow/c/c_api.cc:326] Operation '{name:'gru1/gru1/while' id:329 op device:{} def:{{{node gru1/gru1/while}} = StatelessWhile[T=[DT_INT32, DT_INT32, DT_INT32, DT_VARIANT, DT_FLOAT, ..., DT_VARIANT, DT_VARIANT, DT_VARIANT, DT_VARIANT, DT_VARIANT], _lower_using_switch_merge=true, _num_original_outputs=48, _read_only_resource_inputs=[], body=gru1_gru1_while_body_181[], cond=gru1_gru1_while_cond_180[], output_shapes=[[], [], [], [], [?,12], ..., [], [], [], [], []], parallel_iterations=32](gru1/gru1/while/loop_counter, gru1/gru1/while/maximum_iterations, gru1/gru1/time, gru1/gru1/TensorArrayV2, gru1/gru1/GRUCellZeroState/zeros, gru1/gru1/strided_slice_1, gru1/gru1/TensorArrayUnstack/TensorListFromTensor, gru1/gru_cell/gates/kernel/Read/Identity, gru1/gru_cell/gates/bias/Read/Identity, gru1/gru_cell/candidate/kernel/Read/Identity, gru1/gru_cell/candidate/bias/Read/Identity, gru1/gru1/CheckSeqLen, gru1/gru1/zeros, gru1/gru1/while/EmptyTensorList, gru1/gru1/while/EmptyTensorList_1, gru1/gru1/while/EmptyTensorList_2, gru1/gru1/while/EmptyTensorList_3, gru1/gru1/while/EmptyTensorList_4, gru1/gru1/while/EmptyTensorList_5, gru1/gru1/while/EmptyTensorList_6, gru1/gru1/while/EmptyTensorList_7, gru1/gru1/while/EmptyTensorList_8, gru1/gru1/while/EmptyTensorList_9, gru1/gru1/while/EmptyTensorList_10, gru1/gru1/while/EmptyTensorList_11, gru1/gru1/while/EmptyTensorList_12, gru1/gru1/while/EmptyTensorList_13, gru1/gru1/while/EmptyTensorList_14, gru1/gru1/while/EmptyTensorList_15, gru1/gru1/while/EmptyTensorList_16, gru1/gru1/while/EmptyTensorList_17, gru1/gru1/while/EmptyTensorList_18, gru1/gru1/while/EmptyTensorList_19, gru1/gru1/while/EmptyTensorList_20, gru1/gru1/while/EmptyTensorList_21, gru1/gru1/while/EmptyTensorList_22, gru1/gru1/while/EmptyTensorList_23, gru1/gru1/while/EmptyTensorList_24, gru1/gru1/while/EmptyTensorList_25, gru1/gru1/while/EmptyTensorList_26, gru1/gru1/while/EmptyTensorList_27, gru1/gru1/while/EmptyTensorList_28, gru1/gru1/while/EmptyTensorList_29, gru1/gru1/while/EmptyTensorList_30, gru1/gru1/while/EmptyTensorList_31, gru1/gru1/while/EmptyTensorList_32, gru1/gru1/while/EmptyTensorList_33, gru1/gru1/while/EmptyTensorList_34)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.
Epoch 1/10
1/1 [==============================] - 0s 357ms/sample - loss: 1.6459 - binary_crossentropy: 0.7021 - val_loss: 1.3913 - val_binary_crossentropy: 0.6920
Epoch 2/10
1/1 [==============================] - 0s 7ms/sample - loss: 1.6219 - binary_crossentropy: 0.6894 - val_loss: 1.3865 - val_binary_crossentropy: 0.6919
Epoch 3/10
1/1 [==============================] - 0s 5ms/sample - loss: 1.6182 - binary_crossentropy: 0.6921 - val_loss: 1.3850 - val_binary_crossentropy: 0.6918
Epoch 4/10
1/1 [==============================] - 0s 5ms/sample - loss: 1.6136 - binary_crossentropy: 0.6894 - val_loss: 1.3859 - val_binary_crossentropy: 0.6918
Epoch 5/10
1/1 [==============================] - 0s 8ms/sample - loss: 1.6159 - binary_crossentropy: 0.6904 - val_loss: 1.3878 - val_binary_crossentropy: 0.6920
Epoch 6/10
1/1 [==============================] - 0s 5ms/sample - loss: 1.6185 - binary_crossentropy: 0.6907 - val_loss: 1.3891 - val_binary_crossentropy: 0.6922
Epoch 7/10
1/1 [==============================] - 0s 5ms/sample - loss: 1.6194 - binary_crossentropy: 0.6902 - val_loss: 1.3892 - val_binary_crossentropy: 0.6923
Epoch 8/10
1/1 [==============================] - 0s 5ms/sample - loss: 1.6001 - binary_crossentropy: 0.6708 - val_loss: 1.3885 - val_binary_crossentropy: 0.6924
Epoch 9/10
1/1 [==============================] - 0s 5ms/sample - loss: 1.6088 - binary_crossentropy: 0.6806 - val_loss: 1.3874 - val_binary_crossentropy: 0.6924
Epoch 10/10
1/1 [==============================] - 0s 5ms/sample - loss: 1.6052 - binary_crossentropy: 0.6785 - val_loss: 1.3863 - val_binary_crossentropy: 0.6924
Traceback (most recent call last):
  File "/home/litchy/pro/local-recommendation/main.py", line 64, in <module>
    tf.saved_model.save(model, 'tf_dien')
  File "/home/litchy/pro/local-recommendation/venv/lib/python3.6/site-packages/tensorflow/python/saved_model/save.py", line 951, in save
    obj, export_dir, signatures, options, meta_graph_def)
  File "/home/litchy/pro/local-recommendation/venv/lib/python3.6/site-packages/tensorflow/python/saved_model/save.py", line 1008, in _build_meta_graph
    checkpoint_graph_view)
  File "/home/litchy/pro/local-recommendation/venv/lib/python3.6/site-packages/tensorflow/python/saved_model/signature_serialization.py", line 75, in find_function_to_export
    functions = saveable_view.list_functions(saveable_view.root)
  File "/home/litchy/pro/local-recommendation/venv/lib/python3.6/site-packages/tensorflow/python/saved_model/save.py", line 143, in list_functions
    self._serialization_cache)
  File "/home/litchy/pro/local-recommendation/venv/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 1656, in _list_functions_for_serialization
    Model, self)._list_functions_for_serialization(serialization_cache)
  File "/home/litchy/pro/local-recommendation/venv/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer_v1.py", line 2439, in _list_functions_for_serialization
    .list_functions_for_serialization(serialization_cache))
  File "/home/litchy/pro/local-recommendation/venv/lib/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/base_serialization.py", line 87, in list_functions_for_serialization
    fns = self.functions_to_serialize(serialization_cache)
  File "/home/litchy/pro/local-recommendation/venv/lib/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/layer_serialization.py", line 77, in functions_to_serialize
    serialization_cache).functions_to_serialize)
  File "/home/litchy/pro/local-recommendation/venv/lib/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/layer_serialization.py", line 92, in _get_serialized_attributes
    serialization_cache)
  File "/home/litchy/pro/local-recommendation/venv/lib/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/model_serialization.py", line 53, in _get_serialized_attributes_internal
    serialization_cache))
  File "/home/litchy/pro/local-recommendation/venv/lib/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/layer_serialization.py", line 101, in _get_serialized_attributes_internal
    functions = save_impl.wrap_layer_functions(self.obj, serialization_cache)
  File "/home/litchy/pro/local-recommendation/venv/lib/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/save_impl.py", line 153, in wrap_layer_functions
    original_fns = _replace_child_layer_functions(layer, serialization_cache)
  File "/home/litchy/pro/local-recommendation/venv/lib/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/save_impl.py", line 272, in _replace_child_layer_functions
    serialization_cache).functions)
  File "/home/litchy/pro/local-recommendation/venv/lib/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/layer_serialization.py", line 92, in _get_serialized_attributes
    serialization_cache)
  File "/home/litchy/pro/local-recommendation/venv/lib/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/layer_serialization.py", line 101, in _get_serialized_attributes_internal
    functions = save_impl.wrap_layer_functions(self.obj, serialization_cache)
  File "/home/litchy/pro/local-recommendation/venv/lib/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/save_impl.py", line 153, in wrap_layer_functions
    original_fns = _replace_child_layer_functions(layer, serialization_cache)
  File "/home/litchy/pro/local-recommendation/venv/lib/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/save_impl.py", line 272, in _replace_child_layer_functions
    serialization_cache).functions)
  File "/home/litchy/pro/local-recommendation/venv/lib/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/layer_serialization.py", line 92, in _get_serialized_attributes
    serialization_cache)
  File "/home/litchy/pro/local-recommendation/venv/lib/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/layer_serialization.py", line 101, in _get_serialized_attributes_internal
    functions = save_impl.wrap_layer_functions(self.obj, serialization_cache)
  File "/home/litchy/pro/local-recommendation/venv/lib/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/save_impl.py", line 191, in wrap_layer_functions
    fn.get_concrete_function()
  File "/home/litchy/pro/local-recommendation/venv/lib/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/save_impl.py", line 546, in get_concrete_function
    self.call_collection.add_trace(*args, **kwargs)
  File "/home/litchy/pro/local-recommendation/venv/lib/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/save_impl.py", line 421, in add_trace
    fn.get_concrete_function(*args, **kwargs)
  File "/home/litchy/pro/local-recommendation/venv/lib/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/save_impl.py", line 547, in get_concrete_function
    return super(LayerCall, self).get_concrete_function(*args, **kwargs)
  File "/home/litchy/pro/local-recommendation/venv/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 959, in get_concrete_function
    concrete = self._get_concrete_function_garbage_collected(*args, **kwargs)
  File "/home/litchy/pro/local-recommendation/venv/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 865, in _get_concrete_function_garbage_collected
    self._initialize(args, kwargs, add_initializers_to=initializers)
  File "/home/litchy/pro/local-recommendation/venv/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 506, in _initialize
    *args, **kwds))
  File "/home/litchy/pro/local-recommendation/venv/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 2446, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/home/litchy/pro/local-recommendation/venv/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 2777, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/home/litchy/pro/local-recommendation/venv/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 2667, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/home/litchy/pro/local-recommendation/venv/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py", line 981, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/litchy/pro/local-recommendation/venv/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 441, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/home/litchy/pro/local-recommendation/venv/lib/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/save_impl.py", line 524, in wrapper
    ret = method(*args, **kwargs)
  File "/home/litchy/pro/local-recommendation/venv/lib/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/save_impl.py", line 566, in call_and_return_conditional_losses
    return layer_call(inputs, *args, **kwargs), layer.get_losses_for(inputs)
TypeError: call() missing 1 required positional argument: 'state'
```

environment:
 - python version 3.6
 - tensorflow version 2.2.0
 - deepctr version master code

**Comment by JiahongFish** [comment]
DIEN returned a keras model. Have you try to use model.save() which from Keras?

**Comment by JiahongFish** [comment]
DIEN returned a Keras model. Have you tried to use model.save() which is from Keras?

**Comment by Litchilitchy** [comment]
> DIEN returned a Keras model. Have you tried to use model.save() which is from Keras?

I changed the line of code to
```
# old code
# tf.saved_model.save(model, 'tf_dien')

# new code
model.save("tf_dien") 
```

the error seems the same,

details:
```
Traceback (most recent call last):
  File "/home/litchy/anaconda3/envs/rec/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/litchy/anaconda3/envs/rec/lib/python3.6/site-packages/tensorflow/python/keras/backend.py", line 423, in learning_phase_scope
    yield
  File "/home/litchy/anaconda3/envs/rec/lib/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/save.py", line 78, in save
    save_lib.save(model, filepath, signatures, options)
  File "/home/litchy/anaconda3/envs/rec/lib/python3.6/site-packages/tensorflow/python/saved_model/save.py", line 951, in save
    obj, export_dir, signatures, options, meta_graph_def)
  File "/home/litchy/anaconda3/envs/rec/lib/python3.6/site-packages/tensorflow/python/saved_model/save.py", line 1008, in _build_meta_graph
    checkpoint_graph_view)
  File "/home/litchy/anaconda3/envs/rec/lib/python3.6/site-packages/tensorflow/python/saved_model/signature_serialization.py", line 75, in find_function_to_export
    functions = saveable_view.list_functions(saveable_view.root)
  File "/home/litchy/anaconda3/envs/rec/lib/python3.6/site-packages/tensorflow/python/saved_model/save.py", line 143, in list_functions
    self._serialization_cache)
  File "/home/litchy/anaconda3/envs/rec/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 1656, in _list_functions_for_serialization
    Model, self)._list_functions_for_serialization(serialization_cache)
  File "/home/litchy/anaconda3/envs/rec/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer_v1.py", line 2439, in _list_functions_for_serialization
    .list_functions_for_serialization(serialization_cache))
  File "/home/litchy/anaconda3/envs/rec/lib/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/base_serialization.py", line 87, in list_functions_for_serialization
    fns = self.functions_to_serialize(serialization_cache)
  File "/home/litchy/anaconda3/envs/rec/lib/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/layer_serialization.py", line 77, in functions_to_serialize
    serialization_cache).functions_to_serialize)
  File "/home/litchy/anaconda3/envs/rec/lib/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/layer_serialization.py", line 92, in _get_serialized_attributes
    serialization_cache)
  File "/home/litchy/anaconda3/envs/rec/lib/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/model_serialization.py", line 53, in _get_serialized_attributes_internal
    serialization_cache))
  File "/home/litchy/anaconda3/envs/rec/lib/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/layer_serialization.py", line 101, in _get_serialized_attributes_internal
    functions = save_impl.wrap_layer_functions(self.obj, serialization_cache)
  File "/home/litchy/anaconda3/envs/rec/lib/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/save_impl.py", line 153, in wrap_layer_functions
    original_fns = _replace_child_layer_functions(layer, serialization_cache)
  File "/home/litchy/anaconda3/envs/rec/lib/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/save_impl.py", line 272, in _replace_child_layer_functions
    serialization_cache).functions)
  File "/home/litchy/anaconda3/envs/rec/lib/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/layer_serialization.py", line 92, in _get_serialized_attributes
    serialization_cache)
  File "/home/litchy/anaconda3/envs/rec/lib/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/layer_serialization.py", line 101, in _get_serialized_attributes_internal
    functions = save_impl.wrap_layer_functions(self.obj, serialization_cache)
  File "/home/litchy/anaconda3/envs/rec/lib/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/save_impl.py", line 153, in wrap_layer_functions
    original_fns = _replace_child_layer_functions(layer, serialization_cache)
  File "/home/litchy/anaconda3/envs/rec/lib/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/save_impl.py", line 272, in _replace_child_layer_functions
    serialization_cache).functions)
  File "/home/litchy/anaconda3/envs/rec/lib/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/layer_serialization.py", line 92, in _get_serialized_attributes
    serialization_cache)
  File "/home/litchy/anaconda3/envs/rec/lib/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/layer_serialization.py", line 101, in _get_serialized_attributes_internal
    functions = save_impl.wrap_layer_functions(self.obj, serialization_cache)
  File "/home/litchy/anaconda3/envs/rec/lib/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/save_impl.py", line 191, in wrap_layer_functions
    fn.get_concrete_function()
  File "/home/litchy/anaconda3/envs/rec/lib/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/save_impl.py", line 546, in get_concrete_function
    self.call_collection.add_trace(*args, **kwargs)
  File "/home/litchy/anaconda3/envs/rec/lib/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/save_impl.py", line 421, in add_trace
    fn.get_concrete_function(*args, **kwargs)
  File "/home/litchy/anaconda3/envs/rec/lib/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/save_impl.py", line 547, in get_concrete_function
    return super(LayerCall, self).get_concrete_function(*args, **kwargs)
  File "/home/litchy/anaconda3/envs/rec/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 959, in get_concrete_function
    concrete = self._get_concrete_function_garbage_collected(*args, **kwargs)
  File "/home/litchy/anaconda3/envs/rec/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 865, in _get_concrete_function_garbage_collected
    self._initialize(args, kwargs, add_initializers_to=initializers)
  File "/home/litchy/anaconda3/envs/rec/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 506, in _initialize
    *args, **kwds))
  File "/home/litchy/anaconda3/envs/rec/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 2446, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/home/litchy/anaconda3/envs/rec/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 2777, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/home/litchy/anaconda3/envs/rec/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 2667, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/home/litchy/anaconda3/envs/rec/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py", line 981, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/litchy/anaconda3/envs/rec/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 441, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/home/litchy/anaconda3/envs/rec/lib/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/save_impl.py", line 524, in wrapper
    ret = method(*args, **kwargs)
  File "/home/litchy/anaconda3/envs/rec/lib/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/save_impl.py", line 566, in call_and_return_conditional_losses
    return layer_call(inputs, *args, **kwargs), layer.get_losses_for(inputs)
TypeError: call() missing 1 required positional argument: 'state'
```

**Comment by JWenBin** [comment]
from tensorflow.python.keras.models import Model, load_model, save_model
save_model(model, outputDir, save_format='h5')

**Comment by Litchilitchy** [comment]
@JWenBin Could save to h5 but could not save to SavedModel

**Comment by YuWentao95** [comment]
@Litchilitchy Did you solve this problem？

**Comment by Litchilitchy** [comment]
> @Litchilitchy Did you solve this problem？

Not yet, posting a colab on tensorflow issue may help, but there is too much code here so I did not finish it so far.
