### ISSUE TITLE
使用din模型的时候，y_pred会出现nan，

### ISSUE THREAD

**Issue by zhangxueren9** [shenweichen/DeepCTR#426]
Please refer to the [FAQ](https://deepctr-doc.readthedocs.io/en/latest/FAQ.html) in doc and search for the [related issues](https://github.com/shenweichen/DeepCTR/issues) before you ask the question.

**Describe the question(问题描述)**
使用din模型的时候，y_pred会出现nan， 我检测了我的输入x是没有nan的。
暂时没有定位到是哪里导致的nan

**Additional context**
Traceback (most recent call last):
  File "C:/Users/lenovo/Desktop/deepin_myprojects/SC-Reseller-NLP/MokkayaRecommend/data_market/example_generator.py", line 224, in <module>
    history = model.fit(x, y, batch_size=256, epochs=10, verbose=2, validation_split=0.0)
  File "C:\Users\lenovo\anaconda3\envs\mokkaya\lib\site-packages\deepctr_torch\models\basemodel.py", line 248, in fit
    loss = loss_func(y_pred, y.squeeze(), reduction='sum')
  File "C:\Users\lenovo\anaconda3\envs\mokkaya\lib\site-packages\torch\nn\functional.py", line 2893, in binary_cross_entropy
    return torch._C._nn.binary_cross_entropy(input, target, weight, reduction_enum)
RuntimeError: all elements of input should be between 0 and 1

**Operating environment(运行环境):**
 - python version [e.g. 3.6]
 - tensorflow version [e.g. 1.4.0, 1.15.0, 2.5.0]
 - deepctr version [e.g. 0.9.0,]

**Comment by zhangxueren9** [comment]
检查过了是我自己模型输入值里面有nan
抱歉
