### ISSUE TITLE
请问m1 mac怎么安装？python版本3.9，tensorflow版本2.5.0

### ISSUE THREAD

**Issue by bill2766** [shenweichen/DeepCTR#449]
在看了[Python 3.8 什么时候支持？](https://github.com/shenweichen/DeepCTR/issues/352)的回答后，我下载了h5py和deepctr --no-deps。
然后运行示例代码后出现以下问题：
```
Traceback (most recent call last):
  File "/Users/trent2766/soft/miniforge3/envs/tfEnvi/lib/python3.8/site-packages/numpy/core/__init__.py", line 22, in <module>
    from . import multiarray
  File "/Users/trent2766/soft/miniforge3/envs/tfEnvi/lib/python3.8/site-packages/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides
  File "/Users/trent2766/soft/miniforge3/envs/tfEnvi/lib/python3.8/site-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: dlopen(/Users/trent2766/soft/miniforge3/envs/tfEnvi/lib/python3.8/site-packages/numpy/core/_multiarray_umath.cpython-38-darwin.so, 0x0002): Library not loaded: @rpath/libcblas.3.dylib
  Referenced from: /Users/trent2766/soft/miniforge3/envs/tfEnvi/lib/python3.8/site-packages/numpy/core/_multiarray_umath.cpython-38-darwin.so
  Reason: tried: '/Users/trent2766/soft/miniforge3/envs/tfEnvi/lib/libcblas.3.dylib' (no such file), '/Users/trent2766/soft/miniforge3/envs/tfEnvi/lib/libcblas.3.dylib' (no such file), '/Users/trent2766/soft/miniforge3/envs/tfEnvi/lib/python3.8/site-packages/numpy/core/../../../../libcblas.3.dylib' (no such file), '/Users/trent2766/soft/miniforge3/envs/tfEnvi/lib/libcblas.3.dylib' (no such file), '/Users/trent2766/soft/miniforge3/envs/tfEnvi/lib/libcblas.3.dylib' (no such file), '/Users/trent2766/soft/miniforge3/envs/tfEnvi/lib/python3.8/site-packages/numpy/core/../../../../libcblas.3.dylib' (no such file), '/Users/trent2766/soft/miniforge3/envs/tfEnvi/lib/libcblas.3.dylib' (no such file), '/Users/trent2766/soft/miniforge3/envs/tfEnvi/bin/../lib/libcblas.3.dylib' (no such file), '/Users/trent2766/soft/miniforge3/envs/tfEnvi/lib/libcblas.3.dylib' (no such file), '/Users/trent2766/soft/miniforge3/envs/tfEnvi/bin/../lib/libcblas.3.dylib' (no such file), '/usr/local/lib/libcblas.3.dylib' (no such file), '/usr/lib/libcblas.3.dylib' (no such file)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/trent2766/code/pcPyCode/DeepCTR/examples/run_din.py", line 1, in <module>
    import numpy as np
  File "/Users/trent2766/soft/miniforge3/envs/tfEnvi/lib/python3.8/site-packages/numpy/__init__.py", line 140, in <module>
    from . import core
  File "/Users/trent2766/soft/miniforge3/envs/tfEnvi/lib/python3.8/site-packages/numpy/core/__init__.py", line 48, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.8 from "/Users/trent2766/soft/miniforge3/envs/tfEnvi/bin/python3"
  * The NumPy version is: "1.19.5"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: dlopen(/Users/trent2766/soft/miniforge3/envs/tfEnvi/lib/python3.8/site-packages/numpy/core/_multiarray_umath.cpython-38-darwin.so, 0x0002): Library not loaded: @rpath/libcblas.3.dylib
  Referenced from: /Users/trent2766/soft/miniforge3/envs/tfEnvi/lib/python3.8/site-packages/numpy/core/_multiarray_umath.cpython-38-darwin.so
  Reason: tried: '/Users/trent2766/soft/miniforge3/envs/tfEnvi/lib/libcblas.3.dylib' (no such file), '/Users/trent2766/soft/miniforge3/envs/tfEnvi/lib/libcblas.3.dylib' (no such file), '/Users/trent2766/soft/miniforge3/envs/tfEnvi/lib/python3.8/site-packages/numpy/core/../../../../libcblas.3.dylib' (no such file), '/Users/trent2766/soft/miniforge3/envs/tfEnvi/lib/libcblas.3.dylib' (no such file), '/Users/trent2766/soft/miniforge3/envs/tfEnvi/lib/libcblas.3.dylib' (no such file), '/Users/trent2766/soft/miniforge3/envs/tfEnvi/lib/python3.8/site-packages/numpy/core/../../../../libcblas.3.dylib' (no such file), '/Users/trent2766/soft/miniforge3/envs/tfEnvi/lib/libcblas.3.dylib' (no such file), '/Users/trent2766/soft/miniforge3/envs/tfEnvi/bin/../lib/libcblas.3.dylib' (no such file), '/Users/trent2766/soft/miniforge3/envs/tfEnvi/lib/libcblas.3.dylib' (no such file), '/Users/trent2766/soft/miniforge3/envs/tfEnvi/bin/../lib/libcblas.3.dylib' (no such file), '/usr/local/lib/libcblas.3.dylib' (no such file), '/usr/lib/libcblas.3.dylib' (no such file)
```

**Comment by zanshuxun** [comment]
在你这个python环境里 import numpy 能成功吗？

**Comment by bill2766** [comment]
> 

能成功。但是在m1，当时好像deepctr与sklearn的numpy版本不兼容。现在我已经使用windows环境能跑了，谢谢。
