### ISSUE TITLE
这是keras版本不对吗？

### ISSUE THREAD

**Issue by Dimitri666** [shenweichen/DeepCTR#453]
Traceback (most recent call last):
  File "E:/testings/DeepCTR-master/examples/run_classification_criteo.py", line 44, in <module>
    model = DeepFM(linear_feature_columns, dnn_feature_columns, task='binary')
  File "E:\testings\DeepCTR-master\deepctr\models\deepfm.py", line 64, in DeepFM
    model = tf.keras.models.Model(inputs=inputs_list, outputs=output)
  File "C:\Users\Lenovo\anaconda3\envs\python37\lib\site-packages\tensorflow\python\training\tracking\base.py", line 629, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "C:\Users\Lenovo\anaconda3\envs\python37\lib\site-packages\keras\engine\functional.py", line 144, in __init__
    for t in tf.nest.flatten(inputs)]):
  File "C:\Users\Lenovo\anaconda3\envs\python37\lib\site-packages\keras\engine\functional.py", line 144, in <listcomp>
    for t in tf.nest.flatten(inputs)]):
  File "C:\Users\Lenovo\anaconda3\envs\python37\lib\site-packages\keras\engine\functional_utils.py", line 48, in is_input_keras_tensor
    return tensor.node.is_input
AttributeError: 'KerasTensor' object has no attribute 'node'

**Comment by StarryCatte** [comment]
同样遇到了这个问题，求解决方法~

**Comment by zangruirui** [comment]
我也遇到了，python3.9
>>> print(tf.__version__)
2.8.0

**Comment by zangruirui** [comment]
> 

这个又解决的吗

**Comment by damvantai** [comment]
I also have this problem

**Comment by 13483910551** [comment]
同样遇到这个问题

**Comment by workingloong** [comment]
应该是tensorflow 版本的问题，试试降低下 TF 版本，我用 TF 2.1.2 没有问题。

**Comment by mingxiaoh** [comment]
meet same problem based on TF2.8

**Comment by mingxiaoh** [comment]
I think the test script need to be updated so as to be compatible with latest TF&keras

**Comment by mingxiaoh** [comment]
I can run it when remove python from python.keras, you all can have a try

**Comment by flyelephant** [comment]
> 应该是tensorflow 版本的问题，试试降低下 TF 版本，我用 TF 2.1.2 没有问题。
tensorflow 版本降到2.5.0可以正常运行
pip install -i https://pypi.tuna.tsinghua.edu.cn/simple deepctr[cpu] tensorflow==2.5.0

**Comment by Gwyndolin777** [comment]
meet the same problem on py3.9 & tf2.9

**Comment by Gwyndolin777** [comment]
after downgrading to tf 2.5.0 ,problem still exists

> meet the same problem on py3.9 & tf2.9

**Comment by Gwyndolin777** [comment]
solved the problem after downgrading to TF 2.5.0

**Comment by shenweichen** [comment]
we have solved this problem in deepctr v0.9.1,please use `pip install -U deepctr` to upgrade latest version.
