### ISSUE TITLE
安装gpu版本报错

### ISSUE THREAD

**Issue by buttogo** [shenweichen/DeepCTR#526]
Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [39 lines of output]
      Traceback (most recent call last):
        File "/app/anaconda3/envs/deepml/lib/python3.7/site-packages/setuptools/_vendor/packaging/requirements.py", line 35, in __init__
          parsed = _parse_requirement(requirement_string)
        File "/app/anaconda3/envs/deepml/lib/python3.7/site-packages/setuptools/_vendor/packaging/_parser.py", line 64, in parse_requirement
          return _parse_requirement(Tokenizer(source, rules=DEFAULT_RULES))
        File "/app/anaconda3/envs/deepml/lib/python3.7/site-packages/setuptools/_vendor/packaging/_parser.py", line 82, in _parse_requirement
          url, specifier, marker = _parse_requirement_details(tokenizer)
        File "/app/anaconda3/envs/deepml/lib/python3.7/site-packages/setuptools/_vendor/packaging/_parser.py", line 132, in _parse_requirement_details
          else "name and no valid version specifier"
        File "/app/anaconda3/envs/deepml/lib/python3.7/site-packages/setuptools/_vendor/packaging/_parser.py", line 149, in _parse_requirement_marker
          span_start=span_start,
        File "/app/anaconda3/envs/deepml/lib/python3.7/site-packages/setuptools/_vendor/packaging/_tokenizer.py", line 168, in raise_syntax_error
          span=span,
      setuptools.extern.packaging._tokenizer.ParserSyntaxError: Expected end or semicolon (after name and no valid version specifier)
          python_version>"3.7"
                        ^
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-cevqrdp3/tensorflow-gpu_b361e39377134e90b866f21e03d26714/setup.py", line 40, in <module>
          setuptools.setup()
        File "/app/anaconda3/envs/deepml/lib/python3.7/site-packages/setuptools/__init__.py", line 106, in setup
          _install_setup_requires(attrs)
        File "/app/anaconda3/envs/deepml/lib/python3.7/site-packages/setuptools/__init__.py", line 77, in _install_setup_requires
          dist.parse_config_files(ignore_option_errors=True)
        File "/app/anaconda3/envs/deepml/lib/python3.7/site-packages/setuptools/dist.py", line 900, in parse_config_files
          self._finalize_requires()
        File "/app/anaconda3/envs/deepml/lib/python3.7/site-packages/setuptools/dist.py", line 597, in _finalize_requires
          self._move_install_requirements_markers()
        File "/app/anaconda3/envs/deepml/lib/python3.7/site-packages/setuptools/dist.py", line 637, in _move_install_requirements_markers
          inst_reqs = list(_reqs.parse(spec_inst_reqs))
        File "/app/anaconda3/envs/deepml/lib/python3.7/site-packages/setuptools/_vendor/packaging/requirements.py", line 37, in __init__
          raise InvalidRequirement(str(e)) from e
      setuptools.extern.packaging.requirements.InvalidRequirement: Expected end or semicolon (after name and no valid version specifier)
          python_version>"3.7"
                        ^
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by Xjh0327** [comment]
如果你环境里已经安装了tf，应该是直接`pip install -U deepctr`就好
`pip install deepctr[gpu]`好像是会再给安装一个tf

**Comment by shenweichen** [comment]
这个报错看起来不是 DeepCTR 本身的问题，而是在安装链路里拉起 `tensorflow-gpu` 时触发的 metadata 解析错误。

建议不要使用 `pip install deepctr[gpu]`。GPU 环境下先根据自己的 Python / CUDA / cuDNN / 系统版本安装匹配的 TensorFlow，然后再安装 DeepCTR 即可，例如：

```bash
pip install -U pip setuptools wheel
pip install "tensorflow==2.10.*"  # 按你的 CUDA/cuDNN/Python 环境选择合适版本
pip install -U deepctr
```

如果环境里已经安装好了 TensorFlow，通常只需要：

```bash
pip install -U deepctr
```

可以先用下面命令确认 TensorFlow 和 GPU 是否正常：

```bash
python -c "import tensorflow as tf; print(tf.__version__); print(tf.config.list_physical_devices('GPU'))"
```

新版 DeepCTR 已不再需要通过 `deepctr[gpu]` 额外安装 GPU 版本；TensorFlow 本身负责 CPU/GPU 支持。
